apiVersion: v1
kind: ConfigMap
metadata:
  name: configs
data:
  default.conf: |
    server {
      listen  80 default server;
      server_name _;

      default_type text/plain;
      location / {
        return 200 '$hostname\n';
      }
    }