apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  labels:
    type: local
spec:
    capacity:
      storage: 10Gi
    accessModes:
    - ReadWriteOnce
    hostPath:
      path: "/tmp/k8s"